site_name: NabBot
site_description: A Discord bot for the MMO Tibia
site_author: Allan Galarza
copyright: >
  © Allan Galarza. All rights reserved.<br>
  <a href="https://www.tibia.com">Tibia</a> is made by <a href="https://www.cipsoft.com/">CipSoft</a>, all Tibia content is copyrighted by <a href="https://www.cipsoft.com/">CipSoft GmbH</a>.


theme:
  name: material
  palette:
    primary: 'deep-purple'
    accent: 'orange'
  logo: 'assets/images/icon.png'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - toc:
        permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - meta
#  - figureAltCaption


google_analytics:
  - UA-111299710-2
  - auto

extra:
  social:
    - type: 'github'
      link: 'https://github.com/NabDev'
    - type: 'globe'
      link: 'https://nabbot.xyz'

repo_url: https://github.com/NabDev/NabBot
edit_uri: ""
nav:
    - Home: index.md
    - Changelog: changelog.md
    - Install Guide: install.md
    - Permissions: permissions.md
    - FAQ: faq.md
    - Features:
      - Overview: features/index.md
      - Autoroles: features/autoroles.md
      - Groups: features/groups.md
      - Watchlist: features/watchlist.md
    - Commands:
      - Overview: commands/index.md
      - Admin commands: commands/admin.md
      - Calculators commands: commands/calculators.md
      - General commands: commands/general.md
      - Info commands: commands/info.md
      - Loot commands: commands/loot.md
      - Mod commands: commands/mod.md
      - Owner commands: commands/owner.md
      - Roles commands: commands/roles.md
      - Tibia commands: commands/tibia.md
      - TibiaWiki commands: commands/tibiawiki.md
      - Timers commands: commands/timers.md
      - Tracking commands: commands/tracking.md
    - Hosting:
      - Configuration: hosting/config.md
      - Messages: hosting/messages.md
      - Cogs: hosting/cogs.md
